### ISSUE TITLE
Invalid grant error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-extractor#30]
400 response s 

```
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

skončí app errorem, ale teda vůbec nevím, jak se to mohlo stát 

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/10/22/07/2018-10-22-07-33-03-5bcd610fedb7e-exception
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/10/22/07/2018-10-22-07-33-04-5bcd611005426-log

**Comment by odinuv** [comment]
tady je konfigurace, ktera to produkuje https://connection.keboola.com/admin/projects/1134/extractors/keboola.ex-google-bigquery/343430998

myslim, ze je autorizovana a ten projekt nebo autorizace smazana na strane googlu

**Comment by ErikZigo** [comment]
Fixed in : https://github.com/keboola/google-bigquery-extractor/pull/40

Je to jak rika odin.
