### ISSUE TITLE
Sync akce: (2) No error message

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-extractor#37]
Stalo se to několikrát za sebou, extraktor sletěl při sync akci `listProjects` s exit kódem `2` a nic neřekl.

https://connection.keboola.com/admin/utils/logs?file=2019/01/18/19/2019-01-18-19-48-08-5c421f6836637-exception

https://connection.keboola.com/admin/utils/logs?file=2019/01/18/19/2019-01-18-19-48-08-5c421f683b9af-log

**Comment by ujovlado** [comment]
![screenshot_2019-01-18_20-57-03](https://user-images.githubusercontent.com/419849/51409996-9f4f5700-1b63-11e9-9150-85ce5f3b7f59.png)

Kliknem edit, zacne to nacitavat "billable project" a spadne to.

Je to konfiguracia z cca pred mesiaca.

**Comment by ErikZigo** [comment]
Spatne se handluje chyba kdyz jsou neplatny credentials.
