### ISSUE TITLE
(2) ErrorException:Undefined index: selfLink

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/google-bigquery-extractor#38]
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/25/13/2019-01-25-13-48-36-5c4b05a4665df-exception

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/25/13/2019-01-25-13-48-36-5c4b05a474b75-log

**Comment by kacurez** [comment]
again
`Query start\nErrorException:Undefined index: selfLink`
https://keboola.slack.com/archives/C09U3R1J4/p1549524788022100

**Comment by ErikZigo** [comment]
Lokalne se mi to deje jen nekdy.

Odpoved pri zalozeni jobu ma obsahovat i `selfLink` coz je URL jobu ktera se pouziva pro polovani.
Po lokalnim debugu to vypada, ze to proste nekdy ten `selfLink` v response nevrati.
